[FIX/REF][3671030][M1902219804694] - caldoor_account_vendor_discount issue fixed
odoo-ps/psus-caldoor pull request #182
Opened 2024-02-13 22:26 UTC by vmac-odoo

### Description
*Please include a summary of the change, the project task link and/or the ID.*
### Changes
- Patch _create_payments to be able to change amount and write_off (explanation in comment)
- Bump version 

Link to task: [#3671031](https://www.odoo.com/web#id=3671031&cids=17&menu_id=6478&action=4043&model=project.task&view_type=form)

### All Submissions:

* [x] My commit respects the [Odoo commit guideline](https://www.odoo.com/documentation/15.0/developer/misc/other/guidelines.html#git)
* [x] My commit message respects the [commit template](https://github.com/odoo-ps/psbe-process/wiki/Commits-message-guidelines#template)
* [ ] I have used pre-commit
* [x] The PR contains **only** my modification and **no other external** commit

### Sh/Runbot:

* [ ] The commits pass test and the branch is green
* [ ] Unit tests have been implemented / standard ones rewritten
* [ ] The Staging is ISO-Prod and will contain only this dev

### Upgrade:

* [ ] The data affected (*if any*) by the changes has been migrated 

### Maintenance reminders:

* Always bump the version of the manifest on the affected modules.
* Notify the developer responsible for the initial development task (when this is relevant).

2024-02-14 23:16 UTC, elce-odoo requested changes
Why are you modifying two modules in a bug fix?

2024-02-14 23:16 UTC, elce-odoo commented on caldoor_account_vendor_discounts/report/print_check.xml
>  </odoo>
line

2024-02-15 18:50 UTC, elce-odoo requested changes

2024-02-15 18:50 UTC, elce-odoo commented on caldoor_account_vendor_discounts/models/account_payment.py
> +                        to_process_grouped[0]['create_vals']['amount'] = move.to_pay - discounts_before_manual
Please take this suggestion into consideration, I'm sure it could still be improved 
´´´
def _validate_move(self, move, to_process_grouped):
    move._compute_to_pay() # idk what this method does here but it seems sus 
    return move.manual_discount and move.to_pay > 0.00 and len(to_process_grouped) >= 1

def update_toprocess_vals(self, to_process, manual_move_ids):
    moves = {move: list(data) for move, data in 
             groupby(to_process, lambda x: x['batch']['lines'].mapped('move_id')) if move.id not in manual_move_ids.ids}

    for move, to_process_grouped in moves.items():
         if self._validate_move(move, to_process_grouped):

            create_vals = to_process_grouped[0]['create_vals']
            group_amount_total = sum(map(lambda vals: vals['amount'], create_vals))

            if group_amount_total != move.to_pay or move.invoice_payment_term_id and len(to_process_grouped) > 0:

                discounts_before_manual = sum(map(lambda x: x['create_vals']['amount'], to_process_grouped[1:])) \
                    if group_amount_total != move.to_pay or move.invoice_payment_term_id else 0
                
                create_vals['write_off_line_vals'] = {
                    'name': f"[Automated] - {self.writeoff_label}",
                    'amount': to_process_grouped[0]['create_vals']['amount'] + discounts_before_manual - move.to_pay,
                    'account_id': self.company_id.vendor_discount_write_off_account.id
                }
                create_vals['amount'] = move.to_pay - discounts_before_manual

def _recalculate_write_offs(self, to_process):
    self.ensure_one()
    manual_move_ids = self.line_ids.filtered(lambda line: line.move_id.manual_discount).move_id
    
    if manual_move_ids and not self.group_payment:
        self.update_toprocess_vals()
´´´

2024-02-19 17:50 UTC, komugi-al requested changes

2024-02-19 17:50 UTC, komugi-al commented on caldoor_account_vendor_discounts/models/account_payment.py
> +    def _create_automated_writeoff(self, amount):
We usually use `_prepare` when we 'prepare' lines for a create

2024-02-19 21:03 UTC, komugi-al approved these changes

2024-02-19 21:03 UTC, komugi-al commented on caldoor_account_vendor_discounts/models/account_payment.py
> +        the amount to_pay, if is different we need to re-calculate it.
This docstring is a but redundant as you're literally explaining the code but we can already get that from reading it, I think it would be better to just explain the general idea of the function

2024-02-19 21:30 UTC, vmac-odoo commented on caldoor_account_vendor_discounts/models/account_payment.py
> +        the amount to_pay, if is different we need to re-calculate it.
fixed

2024-02-19 22:22 UTC, merged